# change the followings to match your Github username and repo name
baseurl: "/wip-eebs" # the name of your github repo
url: "https://BCDigSchol.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Early English Book Subscribers"
description: Early English Book Subscribers

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# nav bar settings and links
nav-menu:
  - title: About
    submenu:
      - title: Publication by Subscription
        link: subpub
      - title: This Project
        link: project
      - title: The Author
        link: author
  - title: Dataset
    submenu:
      - title: EEBS Dataset
        link: dataset
      - title: Conventions
        link: conventions
      - title: Data Dictionary
        link: dictionary
  - title: Initial Findings
    submenu:
      - title: Gender and Genre
        link: gender-and-genre
      - title: Class and Education
        link: class-and-education
      - title: Notable Bibliophiles
        link: bibliophiles
  - title: Further Readings
    link: further-readings
  - title: Home
    link: index

# sets whether a search bar appears on the site header
# NOTE, you will have to increase the site of teh $site-header-height in _sass/theme-settings.scss to to see the search bar
search-bar: false

hide-footer: false # set to true to hide the footer
footer-message: Early English Book Subscribers, 2023 Capstone Project | CC BY-NC License
footer-submessage:  Graduate Certificate in Digital Humanities, Boston College
footer-submessage-link: https://ds.bc.edu

# google-analytics: // if you want to use Google analytics, include your ID here

# sets number of items display per page, if using a blog
paginate: 5

include:
  - _pages

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-paginate
